clc;
clearvars;
close all;
workspace;
cover_image = imread('man.jpg');
secret_image = imread('hat.jpg');
[cover_image,secret_image] = resize_images(cover_image, secret_image);
subplot(2,2,1);
imshow(cover_image);
subplot(2,2,2);
imshow(secret_image);
secret_key = 100;
alpha = 0.99;
stego_image = encode(secret_image,cover_image,secret_key,alpha);
subplot(2,2,3);
imshow(uint8(stego_image));
decoded_secret_image = decode(stego_image, cover_image, secret_key,alpha); 
subplot(2,2,4);
imshow(uint8(decoded_secret_image));
